#!/usr/bin/env ruby
require 'cucumber'
require 'cucumber/rake/task'
require 'yard'
require 'rake'

########################### DEFAULT TASK ############################
desc "This is the default rake task"
task 'default' do | t, arg |
  Rake::Task['kickstarter'].invoke(arg)
end

########################### BASE TASKS ############################
desc "This is the default rake task for kickstarter"
task 'kickstarter' do | t, arg |
  Cucumber::Rake::Task.new('kickstarter') do | t |
    arg = { :controller => 'CONTROLLER=firefox'}.merge(arg)
    t.cucumber_opts = "--require features/"
    t.cucumber_opts.push("--require features/support/")
    t.cucumber_opts.push(arg.values.join(' '))
  end
end

########################### YARD DOC TASK ###########################
YARD::Rake::YardocTask.new do |t|
  t.files   = %w(features/**/*.rb)
  t.files   = %w(lib/**/*.rb)
  t.options = [ '--list-undoc' ]
end